---
commitizen:
  bump_message: 'bump(lan867x): $current_version -> $new_version'
  post_bump_hooks: python ../tools/annotate.py lan867x
  pre_bump_hooks: python ../tools/changelog.py lan867x
  tag_format: lan867x-v$version
  version: 1.0.3
  version_files:
  - 'idf_component.yml:^version: '
  version_scheme: semver
